### ISSUE TITLE
zcash_client_sqlite: Add transparent transaction support for iOS and Android SDKs

### ISSUE THREAD

**Issue by gmale** [zcash/librustzcash#215]
As a mobile native app developer, I'd like to leverage the exposed functionality of librustzcash in order to support transparent transactions.

**Criteria:**
- [x] the SDK supports sending from t -> z
- [x] the SDK supports sending t->t
- [x] the SDK supports [deriving t-addresses](https://github.com/zcash/librustzcash/issues/270) from the same seed or keys used for shielded transactions
- [x] the SDK supports processing transactions with transparent inputs or outputs from lightwalletd

### Open Questions:
- **How will SDK users create t-addresses?**
    - Will key derivation happen inside librustzcash with something like `secp256k1`
    - Or will we have to use an external 3rd party implementation, similar to [how zecwallet-cli does things](https://github.com/adityapk00/zecwallet-light-cli/blob/5d385852518f33a84c69ef82bb8c01f75dcd4f9b/lib/src/lightwallet.rs#L138-L149)?
    - This looks like it will also involve [creating a public key from the secret key and then hashing it and doing a base58 check](https://github.com/adityapk00/zecwallet-light-cli/blob/master/lib/src/lightwallet.rs#L747-L756)
- **How will the SDK and librustzcash coordinate with UTXOs?**
    - The SDK will probably download all UTXOs from lightwalletd
    - librustzcash will need access to the UTXOs that have been downloaded
    - this might be a great test case for the data access API
- **How will the SDK construct transactions that have transparent inputs?**
    - Option 1: create a different function 
    - Option 2: add parameters to the existing function
        - 2a: add `utxos` parameter that require knowledge of specific UTXOs
        - 2b: add `transparentValue` parameter that does not require knowledge of specific UTXOs
- **How will the SDK handle transparent transaction information downloaded from lightwalletd?**
    - It seems that we'd need to parse the bytes using zcash_primitives, then process & store the results with the sqlite crate
    - Shielded outputs can mostly be processed using `decrypt_and_store_transaction` but there are some potential bugs like "is_change" and "nf" being set to null which violates the DB schema which defines them as "not null"
    - We don't have great support for processing transparent outputs, particularly in mixed transactions
    - For a given transaction we need to:
      - iterate over all inputs to check whether this transaction spends any of our UTXOs
      - iterate over all outputs to collect all that match any of our t-addrs
      - decrypt all shielded outputs and find and process those that match our wallet (including TXs that we've sent)

**Note:**
This might be a good test case for integrating with the [data access API](https://github.com/zcash/librustzcash/issues/142). In fact, I'd even suggest that this feature not be implemented without it in place.

**Comment by gmale** [comment]
Note: on the Kotlin side, this library looks promising for doing Eliptic Curve Digital Signature Algorithm (ecdsa) things:
https://github.com/carterharrison/ecdsa-kotlin

**Comment by pacu** [comment]
Swift has https://github.com/Boilertalk/secp256k1.swift

**Comment by gmale** [comment]
We probably need some guidance from core on whether we can use things that exist within librustzcash in order to create t-addrs.

**Comment by gmale** [comment]
As it relates to sending funds, we want to enable sending funds from t2t and t2z. We should discuss approaches:
- Do we want to just create another version of create_to_address?
- OR do we want to begin exposing the transaction builder?

This very closely relates to the concept of a "safe-and-convenient-layer" that is discussed in detail by @nathan-at-least here:
https://github.com/zcash/librustzcash/pull/207

**Comment by gmale** [comment]
TODO: add details here about how we might go about creating transactions with shielded inputs.

we'll have to decide on the right level of abstraction

**Comment by gmale** [comment]
Added details to the issue description about downloading t-addr information from lightwalletd. Long story short, in the wallet, we need to be able to display information about transparent outputs.

**Comment by gmale** [comment]
I split out the T-addr work into separate issue and added details to it
https://github.com/zcash/librustzcash/issues/270

**Comment by geffenz** [comment]
Closing!
